### PR TITLE
Enemy rotation fix

### PR DESCRIPTION
**Pull request by kyleyang2020**
enemy will now attack when player is in range, range is under melee enemy in my scene.
currently its only for melee enemies, as i have not yet implemented it for the other one, but same concept.
to edit the range, change the collider under the melee enemy

### CODE REVIEW

**Comment by kyleyang2020** [comment]
completed implementation for range enemy as well same as melee, edit the range by moving the detection range box collider under the enemy.

**Review by TheStress — COMMENTED** [review]
Make sure you apply your changes to the prefab for both enemies

**Comment by kyleyang2020** [comment]
ive updated the prefabs and named them as new, idk what ive done to the old prefabs and its giving a conflict now, what should i do

**Review by TheStress — APPROVED** [review]
Request Changes:
- [ ] add your changes to the original prefabs, the enemy prefabs that dont include "new" (this is so that peoples levels with the original prefabs have those changes)

After a quick change its good, I fixed the conflicts and added the new component to yours but we want it on the original

**Comment by kyleyang2020** [comment]
ive updated them, let me know if they arent in the right place or anything

**Pull request merged**
